image: nativecode/deno-build:0.1.0

stages:
  - test
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.configure-publish:
  stage: publish
  artifacts:
    paths:
      - dist
  before_script:
    - mkdir dist
    - source .ci-env.sh
    - bash .citools/setup-git ${BUILD_REPO_BRANCH} ${BUILD_REPO_GIT} ${BUILD_REPO_EMAIL}
    - bash .citools/setup-ssh ${BUILD_REPO_DOMAIN} ${BUILD_REPO_SSHKEY_PATH} ${BUILD_REPO_DOMAIN_SSH}

test:
  stage: test
  script:
    - deno run --allow-net https://raw.githubusercontent.com/nativecode-dev/dent/v0.0.0/connector/mod_run.ts localhost --port 5672
    - deno run --allow-net https://raw.githubusercontent.com/nativecode-dev/dent/v0.0.0/connector/mod_run.ts localhost --port 6379
    - deno run --allow-env --allow-read --allow-write --unstable https://raw.githubusercontent.com/nativecode-dev/dent/v0.0.0/dent-cli/mod_run.ts
    - deno test --allow-env --allow-read --allow-net --allow-write --config tsconfig.json --unstable
  services:
    - couchdb:2
    - rabbitmq:3-management-alpine
    - redis:6-alpine
  variables:
    COUCHDB_USER: guest
    COUCHDB_PASSWORD: guest
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest

prerelease:
  extends: .configure-publish
  script:
    - deno bundle -c tsconfig.json --unstable run.ts dist/mod.ts
    - npx standard-version --prerelease beta
    - git push --follow-tags origin develop
  only:
    - develop

release:
  extends: .configure-publish
  script:
    - deno bundle -c tsconfig.json --unstable run.ts dist/mod.ts
    - npx standard-version
    - git push --follow-tags origin master
  only:
    - master
