image: nativecode/deno:0.2.0

stages:
  - test
  - publish

test:
  stage: test
  script:
    - deno run --allow-net https://raw.githubusercontent.com/nativecode-dev/dent/master/connector/mod_run.ts localhost --port 5672
    - deno run --allow-net https://raw.githubusercontent.com/nativecode-dev/dent/master/connector/mod_run.ts localhost --port 6379
    - deno run --allow-env --allow-read --allow-write --unstable https://raw.githubusercontent.com/nativecode-dev/dent/master/dent-cli/mod_run.ts
    - deno test --allow-env --allow-read --allow-net --allow-write --config tsconfig.json --unstable
  services:
    - couchdb:2
    - rabbitmq:3-management-alpine
    - redis:6-alpine
  variables:
    COUCHDB_USER: admin
    COUCHDB_PASSWORD: password
    RABBITMQ_DEFAULT_USER: admin
    RABBITMQ_DEFAULT_PASS: password
publish:
  stage: publish
  script:
    - mkdir dist
    - deno bundle --config tsconfig.json --unstable mod.ts dist/mod.ts
  only:
    - master
  artifacts:
    paths:
      - dist
